# permissions for end users to view multisites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multisite-viewer-role
rules:
- apiGroups:
  - jcy.ismewen.com
  resources:
  - multisites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jcy.ismewen.com
  resources:
  - multisites/status
  verbs:
  - get
